### ISSUE TITLE
Strange IP being used for populateChannels

### ISSUE THREAD

**Issue by CraziFuzzy** [enternoescape/opendct#299]
I have noticed a lot of these errors in my logs.  I really have no idea where this IP is coming from, as it's nothing like any IP on my network (which is all 192.168.99.xxx, with the prime being 192.168.99.30).  The prime is functioning fine otherwise, and being reported properly in the logs, so not sure why this particular call is getting it wrong.
```
11:07:45.257 [HDHomeRunDiscoveryReceive-43] INFO  ChannelManager - Updating the HDHomeRun channel lineup HDHomeRun DRI Tuner 13112BC2 (dct_hdhomerun).
11:07:45.257 [HDHomeRunDiscoveryReceive-43] INFO  HDHomeRunChannels - Connecting to Prime DCT using the URL 'http://198.105.254.24:80/lineup.xml'
11:07:46.292 [HDHomeRunDiscoveryReceive-43] DEBUG HDHomeRunChannels - populateChannels created an unexpected exception => java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at opendct.channel.updater.http.HDHomeRunChannels.populateChannels(HDHomeRunChannels.java:173)
	at opendct.channel.ChannelManager.updateChannelLineup(ChannelManager.java:484)
	at opendct.capture.HDHRNativeCaptureDevice.<init>(HDHRNativeCaptureDevice.java:225)
	at opendct.tuning.hdhomerun.HDHomeRunDiscoveredDevice.loadCaptureDevice(HDHomeRunDiscoveredDevice.java:86)
	at opendct.tuning.discovery.discoverers.HDHomeRunDiscoverer.loadCaptureDevice(HDHomeRunDiscoverer.java:666)
	at opendct.tuning.discovery.DeviceLoaderImpl.advertiseDevice(DeviceLoaderImpl.java:49)
	at opendct.tuning.discovery.discoverers.HDHomeRunDiscoverer.addCaptureDevice(HDHomeRunDiscoverer.java:520)
	at opendct.tuning.hdhomerun.HDHomeRunDiscovery$ReceiveThread.run(HDHomeRunDiscovery.java:429)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by enternoescape** [comment]
I think I know why that's happening. Originally OpenDCT saved the IP address off the HDHomeRun device, but later to help if the IP address changed, it started to write out the unique HDHomeRun hex device ID and then it would look up the current IP address. There's a test to determine if the lineup has an IP address or hex and I think Java might actually be able to parse the hex as a valid IP address.

**Comment by enternoescape** [comment]
I changed how it's determined that we should be using a literal IP address. Let me know if that works better.
